<html>
<link rel="stylesheet" href="<?=BASICURL?>public/css/common.css" type="text/css">
<script type="text/javascript" src="<?=BASICURL?>public/js/public.js"></script>
<body>

<form action="../index/login" method="post">
Name: <input type="text" name="name"><br>
E-mail: <input type="text" name="email"><br>
<input type="hidden" value="1" name="submit">
<input type="submit">
</form>
<div>1</div>

</body>
</html>